In [ ]:
import pandas as pd
from datasets import load_dataset


dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'], errors='coerce') #transformar em datetime

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df['job_posted_date'] = df['job_posted_date'].dt.date

df.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."

In [5]:
df.sort_values(by='job_posted_date', ascending=False, inplace=True)
df.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
287457,Senior Data Engineer,Senior Data Engineer,"Randburg, South Africa",via CareerJunction,Full-time,False,South Africa,2023-12-31,False,False,South Africa,NaN,NaN,NaN,DCV Sabenza IT and Recruitment,"['sql', 'python', 'databricks', 'azure', 'hado...","{'analyst_tools': ['ssrs', 'power bi', 'tablea..."
646083,Data Scientist,DATA SCIENTIST regio Utrecht – PHARMO Institut...,"Nieuwegein, Netherlands",via Utrecht.work,Full-time,False,Netherlands,2023-12-31,False,False,Netherlands,NaN,NaN,NaN,Nationale Vacaturebank,NaN,NaN
114666,Senior Data Engineer,Senior Data Engineer (Python),"Wichita Falls, TX",via LinkedIn,Full-time and Part-time,False,Georgia,2023-12-31,False,True,United States,NaN,NaN,NaN,ClickJobs.io,"['python', 'java', 'scala', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."

In [6]:
df.dropna(subset=['salary_year_avg'], inplace=True) #para remover valores nan
df.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
574802,Senior Data Analyst,Senior Reporting Analyst,"Iowa City, IA",via Ladders,Full-time,False,"Illinois, United States",2023-12-31,False,True,United States,year,95150.0,NaN,CVS Health,"['sql', 't-sql', 'sql server', 'ssrs', 'tableau']","{'analyst_tools': ['ssrs', 'tableau'], 'databa..."
120858,Data Analyst,Machine Learning Data Analyst,Anywhere,via Get.It,Full-time,True,"California, United States",2023-12-31,False,True,United States,year,144000.0,NaN,Get It Recruit - Information Technology,"['sql', 'python', 'matplotlib', 'tableau', 'po...","{'analyst_tools': ['tableau', 'power bi'], 'li..."
122037,Data Scientist,"Data Scientist, Principal","Mid Florida, FL",via Ladders,Full-time,False,"Florida, United States",2023-12-31,False,True,United States,year,137500.0,NaN,"Blackbaud, Inc.","['python', 'r', 'databricks', 'azure']","{'cloud': ['databricks', 'azure'], 'programmin..."

In [7]:
df['job_title_short'].value_counts().head(3) #contar valores de cada trabalho

job_title_short
Data Scientist    5922
Data Analyst      5451
Data Engineer     4500
Name: count, dtype: int64

In [10]:
#exemplo de groupby
df.groupby('job_title_short')['salary_year_avg'].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [11]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max'])

                               min       max
job_title_short
Business Analyst           16500.0  387460.0
Cloud Engineer             42000.0  280000.0
Data Analyst               25000.0  650000.0
Data Engineer              15000.0  525000.0
Data Scientist             27000.0  960000.0
Machine Learning Engineer  30000.0  325000.0
Senior Data Analyst        30000.0  425000.0
Senior Data Engineer       35000.0  425000.0
Senior Data Scientist      45000.0  890000.0
Software Engineer          28000.0  375000.0

In [13]:
#agora, alguns exercícios

us_jobs = df[df['job_country'] == 'United States'] #separa apenas jobs dos eua
us_jobs.groupby('job_title_short')['salary_year_avg'].mean().sort_values(ascending=False).head(5) # faz o groupby, e coloca em ordem decrescente

job_title_short
Senior Data Scientist        159330.432029
Machine Learning Engineer    154240.382812
Senior Data Engineer         151448.023186
Data Scientist               139946.707204
Software Engineer            137964.929588
Name: salary_year_avg, dtype: float64

In [14]:
us_jobs.groupby('job_title_short').size().sort_values(ascending=False) #pega a contagem de cada trabalho

job_title_short
Data Scientist               4553
Data Analyst                 4350
Data Engineer                2915
Senior Data Scientist        1241
Senior Data Engineer         1058
Senior Data Analyst           913
Business Analyst              431
Software Engineer             157
Machine Learning Engineer     128
Cloud Engineer                 20
dtype: int64

In [15]:
#exemplo final

us_jobs.groupby('job_title_short')['salary_year_avg'].agg(['median', 'min', 'max', 'count']).sort_values(by='median', ascending=False)

                             median      min       max  count
job_title_short
Senior Data Scientist      155000.0  55000.0  475000.0   1241
Machine Learning Engineer  150000.0  44408.5  315000.0    128
Senior Data Engineer       150000.0  45000.0  375000.0   1058
Data Scientist             130000.0  30000.0  960000.0   4553
Software Engineer          130000.0  48982.0  375000.0    157
Data Engineer              125000.0  23496.0  525000.0   2915
Cloud Engineer             116100.0  42000.0  221844.0     20
Senior Data Analyst        110000.0  35360.0  425000.0    913
Business Analyst            90000.0  35000.0  387460.0    431
Data Analyst                90000.0  25000.0  375000.0   4350